export * from './alert/alert.component';
export * from './discovery/discovery.component';
export * from './feedback/feedback.component';
export * from './home/home.component';
export * from './login/login.component';
export * from './navbar/navbar.component';
export * from './register/register.component';
export * from './schemes/schemes.component';
export * from './user/user.component';
